name: Health Endpoints Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-health-endpoints:
    runs-on: ubuntu-latest
    name: Test Health Endpoints
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install expect
      run: |
        sudo apt-get update
        sudo apt-get install -y expect
    
    - name: Run health endpoints test
      run: |
        echo "Testing health endpoints in generated projects..."
        node test/test-health-endpoints.js
      env:
        CI: true
    
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: health-test-results
        path: test-output/