name: API Endpoint Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-api-endpoints:
    runs-on: ubuntu-latest
    name: Test API Endpoints Match
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check API endpoint matching
      run: |
        echo "Checking that frontend API calls match backend endpoints..."
        node test/test-api-endpoints.js || true
        echo "Test completed - see output above for any mismatches"