# DISABLED: This workflow has been replaced by Kedro test orchestration
# To run manually, use workflow_dispatch in GitHub Actions UI

name: Docker Integration Test

on:
  workflow_dispatch:  # DISABLED - use CI with Kedro instead
  # Original triggers disabled - see git history
  push:
    branches: [main, develop, release/*]
  pull_request:
    branches: [main]
    paths:
      - 'templates/common/backend/**'
      - 'templates/common/docker-compose.yml'
      - 'templates/common/database/**'
      - 'templates/frontend-*/**'
      - 'test/test-docker-compose.js'
      - '.github/workflows/test-docker-integration.yml'

jobs:
  docker-integration:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Run Docker Integration Test
        run: npm run test:docker
        timeout-minutes: 10
        
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: |
            /tmp/stackwizard-docker-test-*/*/docker-compose.logs
            /tmp/stackwizard-docker-test-*/*/.env