name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      
permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    
    - name: Get current version
      id: current
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $CURRENT_VERSION"
    
    - name: Bump version
      id: bump
      run: |
        # Bump version based on input
        npm version ${{ github.event.inputs.version-type }} --no-git-tag-version
        
        # Get new version
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "New version: $NEW_VERSION"
    
    - name: Create release branch
      run: |
        BRANCH_NAME="release/v${{ steps.bump.outputs.new-version }}"
        git checkout -b $BRANCH_NAME
        git add package.json package-lock.json
        git commit -m "chore: bump version to ${{ steps.bump.outputs.new-version }}"
        git push -u origin $BRANCH_NAME
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/v${{ steps.bump.outputs.new-version }}
        base: main
        title: "chore: Release v${{ steps.bump.outputs.new-version }}"
        body: |
          ## 🚀 Release v${{ steps.bump.outputs.new-version }}
          
          This PR bumps the version from `${{ steps.current.outputs.version }}` to `${{ steps.bump.outputs.new-version }}`.
          
          ### Version Bump Type
          - **Type**: ${{ github.event.inputs.version-type }}
          
          ### Checklist
          - [ ] All tests pass
          - [ ] Documentation updated (if needed)
          - [ ] CHANGELOG updated (if exists)
          
          ---
          
          After merging this PR, the package will be automatically published to NPM.
          
          🤖 Auto-generated by GitHub Actions
        labels: |
          release
          version-bump
          automated